spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yunbi?useSSL=false&serverTimezone=UTC
    username: qianfang
    password:

  # Spring AI 配置
  ai:
    openai:
      base-url: https://api.siliconflow.cn
      api-key: ${API_KEY:}
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3

# 日志配置
logging:
  level:
    com.qfleaf: debug

# jjwt自定义配置
jwt:
  secret: ${JWT_SECRET:jWk6x9Q2s@L8p!FdZ#rM7cY^tBhNvTgR$eW3kUzPqJoX1zAsCmYvGeLaKdR0fHqI} # 实际部署替换环境变量
  expiration:
    refresh-token: 86400000 # 24小时 (604800000  # 7天)
    access-token: 900000 # 15分钟